<?php

namespace Plemi\Bundle\BoomgoBundle\Tests\Mapper;

use Boomgo\Mapper\MapperProvider,
    Boomgo\Mapper\MapperInterface;

/**
 * EmbedAnnotationMapper
 *
 * Auto generated Mapper class for/by Boomgo
 * Do not edit this file
 *
 * @author  Boomgo\Generator\MapperGenerator
 */
class EmbedAnnotationMapper extends MapperProvider implements MapperInterface
{
    /**
     * Unserialize a MongoDB array to an object
     *
     * Return an hydrated object from a MongoDB array
     *
     * @param  array  $data MongoDB result array (a document)
     *
     * @return \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation
     */
    public function unserialize(array $data)
    {
        $object = new \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation();
        $this->hydrate($object, $data);

        return $object;
    }

    /**
     * Serialize an object to a MongoDB array
     *
     * Return an Mongo-able array from a Php object
     *
     * @param  \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation $object
     *
     * @return array
     */
    public function serialize($object)
    {
        if (!$object instanceof \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation) {
            throw new \InvalidArgumentException('Serialize expect an instance of "\Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation"');
        }

        $data = array();
        
        $value = $object->getString();
        if (null != $value && !empty($value)) {
            $data['string'] = $value;
        }
        
        $value = $object->getArray();
        if (null != $value && !empty($value)) {
            $data['array'] = $this->normalize($value);
        }
        
        return $data;
    }

    /**
     * Hydrate an object from a MongoDb array
     *
     * @param  \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation $object
     * @param  array $data MongoDB result array (a document)
     */
    public function hydrate($object, array $data)
    {
        if (!$object instanceof \Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation) {
            throw new \InvalidArgumentException('Serialize expect an instance of "\Plemi\Bundle\BoomgoBundle\Tests\Document\EmbedAnnotation"');
        }
        
        if (isset($data['string'])) {
            $object->setString($data['string']);
        }
        
        if (isset($data['array'])) {
            $object->setArray($data['array']);
        }
        
    }
}